import type { PrintableTemplate, TemplateInputDefinition } from "../types";

const answerLine = (
  question: number,
  xPercent: number,
  lineYPercent: number,
  widthPercent = 3.0,
): TemplateInputDefinition => ({
  inputId: `question_${question}_answer`,
  typeId: "textLine",
  label: `Question ${question} answer`,
  notes: {
    32: "Question 32: Have any of your children ever experienced any type of physical, verbal or sexual abuse by a person outside your family? Enter the selected letter. Choices: a Yes; b No.",
    33: "Question 33: Have any of your children ever experienced any type of physical, verbal or sexual abuse by a person inside your family? Enter the selected letter. Choices: a Yes; b No.",
    34: "Question 34: Do any of your children currently have or had in the past problems with alcohol, prescription drugs or street drugs? Enter the selected letter. Choices: a Yes; b No.",
    35: "Question 35: Do any of your children have special learning needs that require a specialist or special education? Enter the selected letter. Choices: a Yes; b No.",
    36: "Question 36: Do any of your children have a history of mental health problems? Enter the selected letter. Choices: a Yes; b No.",
    37: "Question 37: Has anyone in your family ever been referred for psychological counseling? Enter the selected letter. Choices: a Yes; b No.",
    38: "Question 38: Overall, I would rate my parenting skills. Enter the selected letter. Choices: a Very Good; b Good; c Bad; d Very Bad.",
    39: "Question 39: Overall, the degree of happiness I feel being a parent is. Enter the selected letter. Choices: a High; b OK; c Low; d Very Low.",
    40: "Question 40: Knowing what you know now about being a parent, would you still be a parent if you could do it all over again? Enter the selected letter. Choices: a Yes; b Probably; c Probably Not; d Absolutely Not.",
    41: "Question 41: Nurturing Parenting is. Enter the selected letter. Choices: a Being a parent 24 hours a day, 365 days a year; b Nurturing your children and yourself; c Making sure the needs of children always come first; d Teaching children to care for others.",
    42: "Question 42: Giving children choices early in life teaches them to make good decisions later in life. Enter the selected letter. Choices: a Giving children choices will never get them to do what you want them to do; b Kids can't handle choices - they feel more secure being told what to do; c Choices can help children learn that there are consequences to the decisions they make; d Kids who have choices generally get into power struggles with their parents.",
    43: "Question 43: Having appropriate expectations for children helps them. Enter the selected letter. Choices: a Learn to feel good about themselves; b Develop trust and security; c Learn to succeed in school; d All the above statements are true.",
    44: "Question 44: Discipline means. Enter the selected letter. Choices: a To guide children by using the rod of correction; b To guide children in learning proper morals; c To teach children to be obedient; d To guide children to learn to respect elders.",
    45: "Question 45: The rights and wrongs that children learn are called. Enter the selected letter. Choices: a Family Morals; b Family Values; c Family Traditions; d Family Customs.",
    46: "Question 46: Empathy means. Enter the selected letter. Choices: a To be aware of the feelings your children express; b To feel what it's like being a child; c To help children get their needs met; d Empathy can be all of these at different times.",
    47: "Question 47: Fear teaches children to respect parent's authority. Enter the selected letter. Choices: a Fear teaches children to disrespect their parents; b It's ok to use fear as long as parents don't overdo it; c Fear teaches children to respect the law; d Fear teaches children to learn to be obedient.",
    48: "Question 48: Children who have a strong sense of personal power. Enter the selected letter. Choices: a Get into power struggles with parents about everything; b Are less influenced by peer pressure; c Is one of the characteristics of a bully; d Have difficulty sharing things with others.",
  }[question],
  bounds: { xPercent, yPercent: lineYPercent - 0.85, widthPercent, heightPercent: 1.7 },
  displaySettings: { useWhiteBackground: true, fontSizePt: 9, textAlign: "left" },
});

export const nurturingSkillsForFamiliesChildrenFamilyKnowledgePage3Template: PrintableTemplate = {
  pageId: "nurturing-skills-for-families-children-family-knowledge-page-3",
  name: "Nurturing Skills for Families Children, Family, and Knowledge Page 3",
  notes:
    "Nurturing Skills Competency Scale page 3. All numbered inputs on this page are short letter-entry lines where the respondent writes the selected answer letter from the visible choices for Questions 32-48. There are no separate Other text fields on this page.",
  backgroundImage: {
    src: "/template-assets/nurturing-skills-for-families-children-family-knowledge-page-3.png",
    widthPx: 1086,
    heightPx: 1448,
    mimeType: "image/png",
  },
  inputDefinitions: [
    answerLine(32, 44.5, 10.7),
    answerLine(33, 44.5, 20.5),
    answerLine(34, 44.5, 31.3),
    answerLine(35, 44.5, 42.2),
    answerLine(36, 44.5, 52.4),
    answerLine(37, 44.5, 62.4),
    answerLine(38, 44.5, 72.9),
    answerLine(39, 44.5, 81.5),
    answerLine(40, 44.5, 91.0),
    answerLine(41, 89.6, 11.8),
    answerLine(42, 89.6, 22.5),
    answerLine(43, 89.6, 36.9),
    answerLine(44, 89.6, 48.3),
    answerLine(45, 89.6, 57.3),
    answerLine(46, 89.6, 66.4),
    answerLine(47, 89.6, 75.0),
    answerLine(48, 89.6, 84.0),
  ],
  layoutSettings: { paperSize: "letter", widthIn: 8.5, heightIn: 11 },
  displaySettings: { backgroundColor: "#ffffff" },
  sourceAssetPath: "ai_context/inbox_template/nurturing-skills-for-families-children-family-knowledge-page-3-03.png",
  updatedAt: "2026-05-14T16:50:37-07:00",
};
