import type {
  PrintableTemplate,
  TemplateCheckOption,
  TemplateInputDefinition,
  TemplateInputTypeId,
} from "../types";

const textField = (
  inputId: string,
  label: string,
  questionText: string,
  xPercent: number,
  yPercent: number,
  widthPercent: number,
  heightPercent: number,
  typeId: TemplateInputTypeId = "textLine",
  fontSizePt = 9,
  notes = "",
): TemplateInputDefinition => ({
  inputId,
  typeId,
  label,
  questionText,
  notes,
  bounds: { xPercent, yPercent, widthPercent, heightPercent },
  displaySettings: {
    useWhiteBackground: true,
    fontSizePt,
    textAlign: "left",
    ...(typeId === "date" ? { dateFormat: "MM/DD/YY" as const } : {}),
  },
});

const option = (
  optionId: string,
  label: string,
  xPercent: number,
  yPercent: number,
  widthPercent: number,
  heightPercent: number,
): TemplateCheckOption => ({
  optionId,
  label,
  value: optionId,
  bounds: { xPercent, yPercent, widthPercent, heightPercent },
});

const programReferralGroup = (): TemplateInputDefinition => ({
  inputId: "referred_programs",
  typeId: "checkbox",
  label: "Referred programs",
  questionText: "What programs are you referring this individual to?",
  notes:
    "The form presents program options as table cells without visible checkboxes. Option bounds cover the visible program cells so selections render as checkmarks in the chosen program cells.",
  bounds: { xPercent: 5.7, yPercent: 81.2, widthPercent: 90.0, heightPercent: 9.9 },
  checkOptions: [
    option("neighborhood_action_councils", "Neighborhood Action Councils", 5.7, 83.8, 30.2, 2.4),
    option("zumba", "ZUMBA", 36.0, 83.8, 28.2, 2.4),
    option("preschool_without_walls", "Preschool Without Walls (PWW)", 64.2, 83.8, 31.5, 2.4),
    option("parenting_classes", "Parenting Classes", 5.7, 86.2, 30.2, 2.4),
    option("yoga", "Yoga", 36.0, 86.2, 28.2, 2.4),
    option("street_craft_youth_digital_lab", "Street Craft Youth Digital LAB", 64.2, 86.2, 31.5, 2.4),
    option("urban_farm", "Urban Farm", 5.7, 88.6, 30.2, 2.4),
    option("thriving_together_youth_development", "Thriving Together Youth Dev.", 36.0, 88.6, 28.2, 2.4),
    option("graphic_design_animation", "Graphic Design Animation", 64.2, 88.6, 31.5, 2.4),
  ],
  displaySettings: { useWhiteBackground: false, fontSizePt: 9, textAlign: "left" },
});

const participantRow = (row: number, yPercent: number): TemplateInputDefinition[] => [
  textField(
    `participant_${row}_name`,
    `Participant ${row} name`,
    `What is participant ${row}'s name?`,
    5.7,
    yPercent,
    30.2,
    2.4,
  ),
  textField(
    `participant_${row}_date_of_birth`,
    `Participant ${row} DOB`,
    `What is participant ${row}'s date of birth?`,
    36.0,
    yPercent,
    20.0,
    2.4,
    "date",
  ),
  textField(
    `participant_${row}_gender`,
    `Participant ${row} gender`,
    `What is participant ${row}'s gender?`,
    56.0,
    yPercent,
    17.0,
    2.4,
  ),
  textField(
    `participant_${row}_ethnicity`,
    `Participant ${row} ethnicity`,
    `What is participant ${row}'s ethnicity?`,
    73.0,
    yPercent,
    22.7,
    2.4,
  ),
];

const childRow = (row: number, yPercent: number): TemplateInputDefinition[] => [
  textField(`child_${row}_name`, `Child ${row} name`, `What is child ${row}'s name?`, 5.7, yPercent, 30.2, 2.4),
  textField(
    `child_${row}_date_of_birth`,
    `Child ${row} DOB`,
    `What is child ${row}'s date of birth?`,
    36.0,
    yPercent,
    20.0,
    2.4,
    "date",
  ),
  textField(`child_${row}_gender`, `Child ${row} gender`, `What is child ${row}'s gender?`, 56.0, yPercent, 17.0, 2.4),
  textField(
    `child_${row}_ethnicity`,
    `Child ${row} ethnicity`,
    `What is child ${row}'s ethnicity?`,
    73.0,
    yPercent,
    22.7,
    2.4,
  ),
];

export const sbccPreventionAndAftercareServicesReferralFormTemplate: PrintableTemplate = {
  pageId: "sbcc-prevention-and-aftercare-services-referral-form",
  name: "SBCC Prevention and Aftercare Services Referral Form",
  notes:
    "One-page Prevention and Aftercare Services Referral Form for SBCC SPA 8. Most fields are boxed table cells. Program referral options are represented as a checkbox group even though the source form shows selectable program cells without explicit checkbox marks.",
  backgroundImage: {
    src: "/template-assets/sbcc-prevention-and-aftercare-services-referral-form.png",
    widthPx: 1103,
    heightPx: 1426,
    mimeType: "image/png",
  },
  inputDefinitions: [
    textField("referral_date", "Referral Date", "What is the referral date?", 87.5, 11.8, 8.5, 2.0, "date", 9),
    textField("case_number", "Case Number", "What is the case number?", 18.8, 17.5, 27.5, 2.0),
    textField("survey_number", "Survey Number", "What is the survey number?", 52.5, 17.5, 27.2, 2.0),
    textField("referral_source_name", "Referral source name", "What is the referral source name?", 11.6, 19.5, 16.0, 2.0),
    textField(
      "referral_source_contact_number",
      "Referral source contact number",
      "What is the referral source contact number?",
      40.0,
      19.5,
      17.0,
      2.0,
      "phoneNumber",
    ),
    textField("referral_source_email", "Referral source email", "What is the referral source email address?", 69.5, 19.5, 25.6, 2.0, "email"),
    textField("participant_address_source", "Participant address", "What is the participant address?", 22.8, 24.3, 72.0, 2.0),
    textField("referral_source_position_title", "Position / Title", "What is the referral source position or title?", 18.0, 26.8, 29.0, 2.0),
    textField(
      "agency_organization",
      "Agency / Organization",
      "What is the referral source agency or organization?",
      48.8,
      26.8,
      46.0,
      2.0,
    ),
    ...participantRow(1, 38.5),
    ...participantRow(2, 40.9),
    ...participantRow(3, 43.3),
    ...childRow(1, 50.4),
    ...childRow(2, 52.8),
    ...childRow(3, 55.2),
    ...childRow(4, 57.6),
    ...childRow(5, 60.0),
    textField("client_phone_number", "Client Phone Number", "What is the client phone number?", 19.4, 62.4, 16.0, 2.0, "phoneNumber"),
    textField("preferred_language", "Preferred Language", "What is the preferred language?", 50.3, 62.4, 14.0, 2.0),
    textField("best_time_to_contact", "Best time to contact", "What is the best time to contact the client?", 79.8, 62.4, 15.2, 2.0),
    textField("address", "Address", "What is the family address?", 11.7, 64.7, 24.0, 2.0),
    textField("city", "City", "What city does the family live in?", 39.0, 64.7, 25.0, 2.0),
    textField("state", "State", "What state does the family live in?", 68.2, 64.7, 4.8, 2.0),
    textField("zip_code", "Zip Code", "What is the family zip code?", 79.0, 64.7, 16.0, 2.0),
    textField(
      "consent_to_be_contacted",
      "Consent to be contacted",
      "Has the family given consent to be contacted?",
      14.8,
      67.2,
      21.0,
      3.2,
      "textLine",
      10,
      "Visible form text shows YES in this field; preserve YES/NO or equivalent consent status.",
    ),
    textField("date_of_consent", "Date of Consent", "What is the date of consent?", 47.2, 66.8, 47.5, 2.4, "date"),
    textField(
      "family_disability_explanation",
      "Family disability explanation",
      "Does anyone in the family have a disability? If yes, please explain.",
      5.8,
      71.4,
      89.8,
      6.4,
      "textArea",
      10,
    ),
    programReferralGroup(),
  ],
  layoutSettings: { paperSize: "letter", widthIn: 8.5, heightIn: 11 },
  displaySettings: { backgroundColor: "#ffffff" },
  sourceAssetPath: "ai_context/inbox_template/sbcc_prevention_and_aftercare_referral.png",
  updatedAt: "2026-05-15T16:10:23-07:00",
};
