import type {
  PrintableTemplate,
  TemplateCheckOption,
  TemplateInputDefinition,
  TemplateInputTypeId,
} from "../types";

const textField = (
  inputId: string,
  label: string,
  xPercent: number,
  yPercent: number,
  widthPercent: number,
  heightPercent = 1.7,
  typeId: TemplateInputTypeId = "textLine",
): TemplateInputDefinition => ({
  inputId,
  typeId,
  label,
  bounds: { xPercent, yPercent, widthPercent, heightPercent },
  displaySettings: {
    useWhiteBackground: true,
    fontSizePt: 9,
    textAlign: "left",
    ...(typeId === "date" ? { dateFormat: "MM/DD/YY" as const } : {}),
  },
});

const option = (
  optionId: string,
  label: string,
  xPercent: number,
  yPercent: number,
  widthPercent: number,
  heightPercent = 1.8,
): TemplateCheckOption => ({
  optionId,
  label,
  value: optionId,
  bounds: { xPercent, yPercent, widthPercent, heightPercent },
});

const section = (
  inputId: string,
  label: string,
  xPercent: number,
  widthPercent: number,
  rows: Array<[string, string, number]>,
): TemplateInputDefinition => ({
  inputId,
  typeId: "checkbox",
  label,
  bounds: { xPercent, yPercent: Math.min(...rows.map((row) => row[2])), widthPercent, heightPercent: 50 },
  checkOptions: rows.map(([optionId, optionLabel, yPercent]) =>
    option(optionId, optionLabel, xPercent + 1.0, yPercent, widthPercent - 2.0),
  ),
  displaySettings: { useWhiteBackground: false, fontSizePt: 9, textAlign: "left" },
});

export const torranceCulturalBrokerNeedsAssessmentTemplate: PrintableTemplate = {
  pageId: "torrance-cultural-broker-needs-assessment",
  name: "Torrance Cultural Broker VCB Initial Contact Needs Assessment",
  backgroundImage: {
    src: "/template-assets/torrance-cultural-broker-needs-assessment.png",
    widthPx: 1086,
    heightPx: 1448,
    mimeType: "image/png",
  },
  inputDefinitions: [
    textField("client_name", "Client name", 19.4, 12.9, 29.3),
    textField("date", "Date", 77.2, 12.9, 14.9, 1.7, "date"),
    section("sobriety_needs", "Sobriety needs", 7.5, 27.8, [
      ["no_need", "No Need", 22.8],
      ["outpatient_treatment", "Outpatient Treatment", 24.6],
      ["residential_treatment", "Residential Treatment", 26.4],
      ["twelve_step", "12-Step", 28.2],
      ["meeting_card", "Meeting Card", 30.0],
      ["sponsor", "Sponsor", 31.8],
      ["other", "Other", 33.6],
    ]),
    section("medical_needs", "Medical needs", 7.5, 27.8, [
      ["no_need", "No Need", 40.3],
      ["physical_exam", "Physical Exam", 42.1],
      ["dental_vision_services", "Dental/Vision Services", 43.9],
      ["immunizations", "Immunizations", 45.7],
      ["pregnancy_testing", "Pregnancy Testing", 47.5],
      ["family_planning", "Family Planning", 49.3],
      ["abortion_adoption", "Abortion/Adoption", 51.1],
      ["prenatal_care", "Prenatal Care", 52.9],
      ["other", "Other", 54.7],
    ]),
    section("legal_needs", "Legal needs", 7.5, 27.8, [
      ["no_need", "No Need", 61.2],
      ["outstanding_warrants", "Outstanding Warrants", 63.0],
      ["dcfs_family_court", "DCFS/Family Court", 66.6],
      ["upcoming_court_dates", "Upcoming Court Date(s)", 70.2],
      ["outstanding_fines", "Outstanding Fines", 72.0],
      ["court_ordered_classes", "Court Ordered Classes", 73.8],
      ["probation_ua_testing", "Probation U.A. Testing", 75.6],
      ["ua_testing", "U.A. Testing", 77.4],
      ["other", "Other", 79.2],
    ]),
    section("psychosocial_needs", "Psycho-social needs", 35.4, 27.6, [
      ["no_need", "No Need", 22.8],
      ["mental_health_counseling", "Mental Health Counseling", 24.6],
      ["psychiatric_assessment", "Psychiatric Assessment", 26.4],
      ["psychiatric_medications", "Psychiatric Medications", 28.2],
      ["parenting_skills", "Parenting Skills", 30.0],
      ["anger_management_skills", "Anger Management Skills", 31.8],
      ["life_skills", "Life Skills", 33.6],
      ["family_relationships", "Family Relationships", 36.6],
      ["self_advocacy", "Self-Advocacy", 38.6],
      ["communication_skills", "Communication Skills", 41.0],
      ["domestic_violence", "Domestic Violence", 42.8],
      ["other", "Other", 44.6],
    ]),
    section("education_needs", "Education needs", 35.4, 27.6, [
      ["no_need", "No need", 51.0],
      ["high_school_diploma", "High School Diploma", 52.8],
      ["ged", "G.E.D.", 54.6],
      ["trade_technical_classes", "Trade/Technical Classes", 56.4],
      ["community_college", "Community College", 58.2],
      ["college", "College", 60.0],
      ["other", "Other", 61.8],
    ]),
    section("vocation_needs", "Vocation needs", 35.4, 27.6, [
      ["no_need", "No Need", 68.8],
      ["job_training", "Job Training", 70.6],
      ["employment_assistance", "Employment Assistance", 72.4],
      ["resume", "Resume", 74.2],
      ["other", "Other", 76.0],
    ]),
    section("miscellaneous_needs", "Miscellaneous needs", 63.1, 28.7, [
      ["no_need", "No Need", 22.8],
      ["food_bank_nutrition", "Food Bank/Nutrition", 24.6],
      ["housing_shelter_referrals", "Housing/Shelter Referrals", 26.4],
      ["transportation", "Transportation", 28.2],
      ["other", "Other", 30.0],
    ]),
    section("financial_assistance_needs", "Financial assistance needs", 63.1, 28.7, [
      ["no_need", "No Need", 35.9],
      ["unemployment_benefits", "Unemployment Benefits", 38.6],
      ["calworks", "Calworks", 42.4],
      ["general_relief", "General Relief", 44.2],
      ["ssi_ssdi", "SSI/SSDI", 46.0],
      ["food_stamps_snap", "Food Stamps/SNAP", 47.8],
      ["medi_cal", "Medi-cal", 49.6],
      ["medicare", "Medicare", 51.4],
      ["california_id_card", "California I.D. Card", 53.2],
      ["social_security_cards", "Social Security Card(s)", 55.0],
      ["birth_certificates", "Birth Certificate(s)", 56.8],
      ["other", "Other", 58.6],
    ]),
    section("family_support_needs", "Family support needs", 63.1, 28.7, [
      ["no_need", "No Need", 64.6],
      ["counseling_parent_caregiver_adult", "Counseling for another parent/caregiver/adult", 66.4],
      ["counseling_children", "Counseling for children", 70.3],
      ["parenting_classes", "Parenting Classes", 72.1],
      ["support_groups", "Support Groups", 73.9],
      ["visitation_monitor", "Visitation monitor", 75.7],
      ["other", "Other", 77.5],
    ]),
    textField("top_need_1", "Top need 1", 27.3, 82.7, 64.3),
    textField("top_need_2", "Top need 2", 27.3, 84.6, 64.3),
    textField("top_need_3", "Top need 3", 27.3, 86.4, 64.3),
    textField("referral_form_completed_by", "Referral form completed by", 34.0, 90.8, 31.2),
    textField("referral_form_completed_date", "Referral form completed date", 72.5, 90.8, 17.6, 1.7, "date"),
  ],
  layoutSettings: { paperSize: "letter", widthIn: 8.5, heightIn: 11 },
  displaySettings: { backgroundColor: "#ffffff" },
  sourceAssetPath: "ai_context/inbox_template/torrance-cultural-broker-needs-assessment-06.png",
  updatedAt: "2026-05-14T16:50:37-07:00",
};
